name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Install dependencies
      run: |
        yarn install --immutable

    - name: Lint the grammar
      run: |
        yarn lint

    - name: Generate syntax
      run: |
        yarn generate

    - name: Test corpus
      run: |
        yarn test
  
  integration-tests:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4.1.7

      - name: Run integration tests
        run: |
          cd integration-tests
          yarn install --immutable
