name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Install dependencies
      run: |
        yarn install

    - name: Generate sintax
      run: |
        yarn generate

    - name: Test corpus
      run: |
        yarn test